### ISSUE TITLE
TS7016: Could not find a declaration file for module 'use-wallet'.

### ISSUE THREAD

**Issue by kickboxer** [aragon/use-wallet#104]
It happens in version 0.9.0. But in 0.8.1 all is ok.

![image](https://user-images.githubusercontent.com/7815336/123619714-1f3c7980-d812-11eb-9db3-2f5df6b8284c.png)

**Comment by PradhumnaPancholi** [comment]
any updates on this?

**Comment by talentlessguy** [comment]
I've put up a PR with a fix to "types" field in package.json

hoping to get it merged

**Comment by PradhumnaPancholi** [comment]
> I've put up a PR with a fix to "types" field in package.json
> 
> hoping to get it merged

Thanks

**Comment by talentlessguy** [comment]
the issue can be closed, thanks to @WissenIstNacht it got merged

so waiting for a npm publish
