### ISSUE TITLE
Error while connecting to Trust wallet on ethereum network

### ISSUE THREAD

**Issue by BalaChandrap** [aragon/use-wallet#110]
Getting an Error.

Expected HTTP 101 response but was '502 Bad Gateway'

**Comment by Jerrryrybon** [comment]
You need to contact Trust Wallet support team directly. Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by WissenIstNacht** [comment]
Hey :)

Could you provide more context? Maybe a code snippet, do I can try to reproduce your problem? The versions you're using?

**Comment by BalaChandrap** [comment]
Hi, I have cloned the repo and updated the wallet connect library version, that solved the issue. The previous issue is because of the old wallet connect version,  Wallet connect protocol have made some changes and it broke lot of old implementations.
