### ISSUE TITLE
WalletConnect not taking options

### ISSUE THREAD

**Issue by andrekat** [aragon/use-wallet#127]
Even though I've set the right WalletConnectConnector options, it is still using "mainnet.infura.io" - is there anything I am missing? I've also tried implementing WalletConnect using a custom connector (which works without using this library). 

My setup:

```
const walletConnectors = {
    injected: {
        supportedChainIds: [environment.CHAIN_ID],
        chainId: [environment.CHAIN_ID]
    },
    walletconnect: {
        chainId: 56,//environment.CHAIN_ID,
        rpcUrl: "https://bsc-dataseed.binance.org/", //environment.CHAIN_URL"",
        pollingInterval: 15000
    },
    walletconnectbsc: () => ({
        web3ReactConnector() {
            return new WalletConnectConnector({
                rpc: {
                    [environment.CHAIN_ID!]: environment.CHAIN_URL!
                },
                qrcode: true,
                pollingInterval: 15000,
            })
        },
        handleActivationError(err: any) {
            if(err instanceof UserRejectedRequestError) {
                return new ConnectionRejectedError()
            }

            return new Error(err)
        }

    })
}
```

connect('walletconnect') shows the connect dialog but returns a 401 of mainnet.infura.io
connect('walletconnectbsc') shows the connect dialog but returns a 401 of mainnet.infura.io

**Comment by shrimpynuts** [comment]
Having same issue, with provided rpcUrl to Alchemy:
```
        <UseWalletProvider
          connectors={{
            walletconnect: {
              rpcUrl: 'https://eth-mainnet.alchemyapi.io/v2/GBjvplStTQ2x1FiAa5-5Qdyv2_8ZBuwe',
            },
          }}
        >
```

However, when trying to use walletconnect, I get "POST https://mainnet.infura.io/v3/ 401" error.

@andrekat did you close this because you've figured out the issue?

**Comment by andrekat** [comment]
you need to set the chainId - check this PR / commit:

https://github.com/aragon/use-wallet/pull/132/commits/fba0fa1f1fd00b187ef3d06bc33e6173f02ccda1

**Comment by shrimpynuts** [comment]
Agh, this was frustrating, but thanks for the solution @andrekat! This should be documented
