### ISSUE TITLE
How to Logout from the account directly from the dapp UI 

### ISSUE THREAD

**Issue by Aaishpra** [aragon/use-wallet#133]
There is an option wallet.reset for disconnect button which just resets the values, but what to do if you actually want to disconnect and logout from the account directly from your application's UI.

**Comment by WissenIstNacht** [comment]
Hey there 👋🏼 🙂 

I'm not sure if I understand your question correctly. Could you give me a more detailed description (step-by-step) of what you're trying to do? Are you using Metamask, by any chance?

**Comment by Aaishpra** [comment]
Hi, @WissenIstNacht  thanks for replying, yes I am using metamask for connecting
writing the steps below -

1.  We are connecting the metamask account using `<div>
          Connect:
          <button onClick={() => wallet.connect()}>MetaMask</button>` or mainly
`wallet.connect()`.

2. After I connect I see my account details on the page.
3. But when I try to disconnect ` <button onClick={() => wallet.reset()}>disconnect</button>`  we are using `wallet.reset()` means just resetting the values instead of actually disconnecting or logging out.

Do you know any method how can I actually Logout or disconnect from the account using this package, or can you guys add another function `wallet.disconnect()` similar to `wallet.connect()` to this package.

**Comment by WissenIstNacht** [comment]
Ok. And you would like that `disconnect()` method to do the same as:
- Opening your metamask extension
- Clicking on the green circle (the one labeled "connected")
- Click on the three vertical dots next to your account
- Click "Disconnect this account"

Is that right? If this is the case, then the answer is no, use-wallet can not do that. Sorry 🙁 

If that's not what you want to do let me know and we can try again 🙂

**Comment by Aaishpra** [comment]
Uhm yes that was what I wanted, no problem if that is not possible.
