### ISSUE TITLE
Connect to another smart contract

### ISSUE THREAD

**Issue by jinghongchan** [aragon/use-wallet#134]
How do you perform function calls on another smart contract using this library?

**Comment by WissenIstNacht** [comment]
Hey there 👋🏼 🙂 

**Short answer**

You don't (check the [Readme](https://github.com/aragon/use-wallet#what-usewallet-is-not)).

**Longer answer**

This library provides a layer of abstraction for wallet connectors in React. This means you can connect to wallet providers using a common interface. This interface gives you access to the information wallets expose.

Performing function calls on a smart contract is a completely different task. As stated in the `Readme`, you can use other libraries like Ethers.js or Web3.js for that.
