### ISSUE TITLE
React Failed to compile after call useWallet from 'use-wallet'

### ISSUE THREAD

**Issue by noberk** [aragon/use-wallet#164]
Please check this issue.

![image](https://user-images.githubusercontent.com/26300918/142134173-c649f89b-31c3-4003-a41e-b2880555767b.png)

![image](https://user-images.githubusercontent.com/26300918/142134143-4a963a3e-6c9f-4649-bcfe-bf6e3b3604c7.png)

**Comment by misha-kiss** [comment]
try this
`
const { connect, status, error } = useWallet();`
