### ISSUE TITLE
No chainId property on UseWalletProvider

### ISSUE THREAD

**Issue by panukettu** [aragon/use-wallet#169]
I mean, am I crazy? But there is no chainId prop to insert into `UseWalletProvider` but the docs seem to mention it everywhere.

This is the definition for the props from the distributed package `0.13.1`

```
declare type UseWalletProviderProps = {
    children: ReactNode;
    connectors: {
        [key: string]: Connector | ConnectorConfig;
    };
    autoConnect: boolean;
    pollBalanceInterval: number;
    pollBlockNumberInterval: number;
};
```

What am I missing? My use-case is simple `wallet_switchEthereumChain/wallet_addEthereumChain` and reflect it on the `useWallet`hook.

**Comment by panukettu** [comment]
Well I managed to solve this by reconnecting to the current connector after doing the `switchChain`:

```

export const useChain = () => {
  const [currentChain, setCurrentChain] = useState<EthereumChain>(chains.kovan)

  const { ethereum, connect, connector } = useWallet()

  const handleChainSwitch = async (newChain: EthereumChain) => {
    try {
      await ethereum.request({
        method: 'wallet_switchEthereumChain',
        params: [{ chainId: newChain.chainId }],
      })
      setCurrentChain(newChain)
      if (connector) {
        connect(connector)
      }
    } catch (switchError: any) {
      // user does not have the chain in wallet
      if (switchError.code === CHAIN_NOT_ADDED_ERROR) {
        try {
          await ethereum.request({
            method: 'wallet_addEthereumChain',
            params: [newChain],
          })
        } catch (addError: any) {
          console.log('Chain add failed', addError)
        }
      }
    }
  }

  return {
    currentChain,
    setChain: handleChainSwitch,
  }
}
```

**Comment by jspeirs** [comment]
I was trying to figure this out too and found in some other comments that the method for assigning chainId has changed and it hasn't been updated in the docs.  Below worked for me.

https://github.com/aragon/use-wallet/issues/173

`
<UseWalletProvider autoConnect={false} 
    connectors={{
        injected: {
            chainId: [1, 4]
        },
        walletlink: { 
            chainId: [1, 4],
            url: '', 
            appName: '', 
            appLogoUrl: ''
        },
    }} >
`
