### ISSUE TITLE
Re-enable support for WalletConnect

### ISSUE THREAD

**Issue by sohkai** [aragon/use-wallet#17]
The WalletConnect connector was having some small issues, and has been disabled by default.

**Comment by sophiacodes** [comment]
hey @sohkai, I'm curious, what are the small issues with the WalletConnect connector?

**Comment by cmagan** [comment]
@sohkai is there any eta on having the walletConnect back?

**Comment by sohkai** [comment]
There were previously build issues with wallet connect: https://github.com/aragon/use-wallet/blob/master/src/connectors.js#L17-L21.

This might be as simple as bumping the web3-react connector package's version, so you're welcome to give it a shot and try it on the examples apps included in the repo!

**Comment by JamesLefrere** [comment]
Should be fixed in #37 :)

**Comment by sohkai** [comment]
Fixed with #37 and released in 0.6!
