### ISSUE TITLE
Trustwallet -  WalletConnect not able to connect on iOS

### ISSUE THREAD

**Issue by yasirkhancse** [aragon/use-wallet#175]
Every time users go to Trustwallet and open WalletConnect and opt for +New Connection on iOS, it says connecting after scanning QR code on desktop and after a few seconds says "Failed to Connect".

I have tried the following:
1. Downgrading web3 to 1.2.11
2. Installing @web3-react/walletconnect-connector

**Comment by WissenIstNacht** [comment]
Hey, thanks for reaching out!

We are aware of the issue. Unfortunately we do not have a solution for it right now.

**Comment by CodeLuca** [comment]
Do you have any idea what the solution is related to @WissenIstNacht

**Comment by WissenIstNacht** [comment]
Yes and no. The issues with WalletConnect come form the underlying web3-react library. We've been in contact, but there hasn't been any useful news so far. So for the time being, we can't do much. I think web3-react is about to release a new version, which might iron things out.
