### ISSUE TITLE
Sign Messages

### ISSUE THREAD

**Issue by alyxdow** [aragon/use-wallet#180]
It's very important for any project to sign messages, and these are standard JSON-RPC client methods, could you add message signing methods to save us from building huge hooks and functions? The problem is that, let's say when building a context, you can't use a hook in a function to get a provider, as a result, you need to build a huge piece of shit just to make a basic function

**Comment by alyxdow** [comment]
Thanks.

**Comment by WissenIstNacht** [comment]
Hey 👋🏼 

Unfortunately, we are currently not planing on expanding use-wallet.
