### ISSUE TITLE
[security] Possible issue

### ISSUE THREAD

**Issue by kamikazebr** [aragon/use-wallet#201]
## Issue
It happens all services using use-wallet in specfic versions, more detail below

![phishing](https://user-images.githubusercontent.com/691510/161190639-a9fc3045-e2d7-4495-bc58-ba2cda0d49a8.png)

### Details

https://github.com/aragon/use-wallet/blob/v0.11.0/src/providers/index.tsx#L19

Acessing that url inside the code above (storageapi.fleek.co url) appended with image show that are insecures images, probably phishing.

I checked since version 0.11.0 its possible happen.

https://github.com/aragon/use-wallet/blob/v0.11.0/src/providers/index.tsx

Below version 0.9.0 it shoudnt happen.

### Suggested Solution
We solved that issue in that version - https://github.com/1hive/use-wallet/tree/v1.1.1

We just put the images inside the package again.

**Comment by mathewmeconry** [comment]
fixed with #205 and released with 0.13.5
