### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in '.../node_modules/use-wallet/dist'

### ISSUE THREAD

**Issue by garbin** [aragon/use-wallet#22]
ERROR in ./node_modules/use-wallet/dist/index-5c8633ab.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/use-wallet/dist'
 @ ./node_modules/use-wallet/dist/index-5c8633ab.js 1:597-615 25:275545-275546 25:275563-275564 25:275595-275596
 @ ./node_modules/use-wallet/dist/index.js
 @ ./app/clients/node/index.jsx

Version use-wallet@0.4.2
any help?

**Comment by sohkai** [comment]
@garbin This definitely seems like a bundling issue; `use-wallet` itself does not require the node `fs` module.

Is your bundler set up to target a browser environment?
