### ISSUE TITLE
New use-wallet supporter

### ISSUE THREAD

**Issue by iquirino** [aragon/use-wallet#253]
Hey guys, I am here to ask if you are open to have a new supporter for this package.
I use it everyday and I am on a long wait for a PR be approved.

I am currently working on my own fork of this package.
https://github.com/iquirino/use-wallet

Can I be part of supporter team or should I just publish a new fork of this package?

Thank you!

**Comment by reuvab** [comment]
Hi. What did you decide to do?

**Comment by iquirino** [comment]
6 month's to receive an answer. This is what motivates me.

**Comment by juliettech13** [comment]
Hey guys - apologies. This package is no longer being maintained by the Aragon team. It's best to fork and upgrade it as you wish.

**Comment by iquirino** [comment]
> Hey guys - apologies. This package is no longer being maintained by the Aragon team. It's best to fork and upgrade it as you wish.

What are you using instead?

**Comment by juliettech13** [comment]
We use [WalletConnect](https://walletconnect.com/) in our new products. 
You can check out the repo for our UI [here](https://github.com/aragon/app).

**Comment by reuvab** [comment]
Thank you @juliettech13 for the answer. This is good to know.

**Comment by juliettech13** [comment]
Of course - what are you buidlgin @reuvab ? Anything else we can support with?

**Comment by iquirino** [comment]
I am currently using https://www.rainbowkit.com/
Dropped the use of use-wallet
