### ISSUE TITLE
Add Sepolia as a supported testnet for Ethereum

### ISSUE THREAD

**Issue by biga816** [aragon/use-wallet#273]
Right now, deprecated testnets are supported for Ethereum, such as Ropsten and Rinkeby.
Sepolia need to be added instead of them.

**Comment by biga816** [comment]
I created a PR for this issue. https://github.com/aragon/use-wallet/pull/274
@WissenIstNacht @mathewmeconry 
Could you take a look?

**Comment by mathewmeconry** [comment]
PR is merged and will be released soon. We need to do some changes in the next few days/weeks because of the wallet connect v1 shut down
