### ISSUE TITLE
How does walletconnect use V2

### ISSUE THREAD

**Issue by daichanghai** [aragon/use-wallet#277]
walletconnect V1 is disabled. How do I use V2

**Comment by peter-thundercore** [comment]
Seems like walletconnect V2 is now supported with the new release`v0.14.0`. However, our team is facing this particular error:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://verify.walletconnect.com') does not match the recipient window's origin
```

This is how we've integrated walletconnect V2 with use-wallet:

```
    <UseWalletProvider
      connectors={{
        walletconnectV2: {
          rpc: rpcInfo,
          projectId: 'abc...',
        },
      }}
    >
      {children}
    </UseWalletProvider>
```

The same error can be reproduced in use-wallet's examples. Any thoughts on resolving this issue?

**Comment by iulianivg** [comment]
This package is not supported anymore sadly 
https://github.com/aragon/use-wallet/issues/253#issuecomment-1630491587

**Comment by daichanghai** [comment]
ok thanks very match
