### ISSUE TITLE
Yarn add fails on @walletconnect dependancy 

### ISSUE THREAD

**Issue by RyRy79261** [aragon/use-wallet#47]
## Description 

Executing `yarn add useWallet` runs as expected until `@walletconnect` attempts to run a post script from its package 
```
error .../node_modules/@walletconnect/qrcode-modal: Command failed.
Exit code: 1
Command: node ./scripts/build-registry.js
```

This is due to a missing file in `@walletconnect` 1.0.17 
Issue listed here: https://github.com/WalletConnect/walletconnect-monorepo/issues/317

**Comment by sohkai** [comment]
@RyRy79261 This appears to be fixed with the latest `@walletconnect/qrcode-modal` release. Cleaning your directory and doing another yarn install should fix it!

**Comment by pedrouid** [comment]
Yeah sorry about that, I just had pushed an update with v1.0.17 and forgot to delete that script but immediately removed it on v1.0.18

**Comment by RyRy79261** [comment]
Thanks for the super quick response @sohkai & @pedrouid ! :D
