### ISSUE TITLE
Unabled to catch connector rejections

### ISSUE THREAD

**Issue by RyRy79261** [aragon/use-wallet#48]
## Description

When running the reference code found in the Readme, when attempting to connect using the `connectorId`: `walletconnect`, if a user closes the modal, a breaking error is displayed `Unhandled Rejection (RejectedActivationError): `

![Screenshot_20200720_142428](https://user-images.githubusercontent.com/10461622/87937417-fc97d180-ca94-11ea-9c22-3e8e9b50710e.png)

I have wrapped the `wallet.activate` in a try catch as well as a lower level class based `componentDidCatch` component but I am unable to intercept this error to prevent a crash

**Comment by RyRy79261** [comment]
@sohkai Is this a WalletConnect rejection issue specifically or is it the handling from `useWallet`'s end?

**Comment by RyRy79261** [comment]
I'm not able to catch this error, I have attempted the following using `try ... catch`'s: 
- Wrapping the app in a class component which uses `componentDidCatch`
- Wrapping the code of the component calling `useWallet`
- Wrapping the call `wallet.activate` function in a try catch

**Comment by sohkai** [comment]
Hey @RyRy79261, did you end up finding out how to catch the error? We're not too familiar with WalletConnect's inner workings and we aren't able to dig further into this at the moment!

**Comment by RyRy79261** [comment]
Hi @sohkai Turned out the issue was how I was calling the activate function in the component, so I can catch the error now. 

I did notice that when I run `deactivate0` this doesn't clear `WalletConnect`'s local storage data
