### ISSUE TITLE
How do i use-wallet to connect to local ganache?

### ISSUE THREAD

**Issue by cryptoseabook** [aragon/use-wallet#55]
How do i use-wallet to connect to local ganache?

It's keep saying, unsupported chain Id. I have no clue. How do i use this test locally?

**Comment by cryptoseabook** [comment]
sorry, i figured out.

**Comment by brockelmore** [comment]
@cryptoseabook what did you do?

**Comment by knyuwork** [comment]
@cryptoseabook May I know how did you connect to local ganache?

**Comment by B1aZer** [comment]
@knyuwork It seems you need to set chainID to 1337.

**Comment by sohkai** [comment]
To add colour to this, ganache-cli in previous versions had hardcoded its chainID to 1337, even with using the `--chainId` flag.

This has been fixed in the most recent version (and the upcoming v7 will continue fixing this), so hopefully the behaviour will become less confusing!
