### ISSUE TITLE
Optionally import wallets to minimize final bundle size

### ISSUE THREAD

**Issue by kali-maha** [aragon/use-wallet#63]
**Issue:**
Big final bundle size even if you want to use only one connection method. 
Bellow i attached the image where you can see that dependencies such as Torus alone gets 23.2% even if it's not being used actively.

**Solution:** 
I didn't go deeply into the repo but making the wallets you would like to use optional by letting `UseWalletProvider` know and installing/importing the wallet dependencies separately could be a solution.

Let me know your thoughts and thanks for maintaining the library 

![Kazam_screenshot_00008](https://user-images.githubusercontent.com/70070731/96293673-6ae42580-0feb-11eb-92ab-e0c070715778.png)

**Comment by bpierre** [comment]
Thanks for reporting an issue! The problem is being addressed in https://github.com/aragon/use-wallet/pull/51

**Comment by kali-maha** [comment]
Thanks @bpierre!
