### ISSUE TITLE
Documentation does not match implementation 

### ISSUE THREAD

**Issue by RyRy79261** [aragon/use-wallet#66]
## Description

Documentation for connecting to Metamask throws error
![image](https://user-images.githubusercontent.com/10461622/96752460-c721bd80-13ce-11eb-86f8-89a82bd97f5c.png)
![image](https://user-images.githubusercontent.com/10461622/96752494-d1dc5280-13ce-11eb-89e4-1a56e1d6a44d.png)

**Comment by cinnabarhorse** [comment]
You should use wallet.connect("injected") for Metamask

**Comment by WissenIstNacht** [comment]
I think this has been updated.
