### ISSUE TITLE
I encountered a problem during use

### ISSUE THREAD

**Issue by 0xlegos** [aragon/use-wallet#68]
When my dapp is not connected to the wallet, the program will not get the contract data. I think the structure is because the Ethereum chainId cannot be obtained without connecting the wallet, or is it something I don’t know? Is there a way to use use-wallet to obtain contract data without connecting to the wallet?

**Comment by 0xlegos** [comment]
It should be how to get the current Ethereum provider without connecting to the wallet

**Comment by sohkai** [comment]
> Is there a way to use use-wallet to obtain contract data without connecting to the wallet?

No, you would want to use a library like `ethers` or `web3` instead.

**Comment by sohkai** [comment]
Closing for now @0xlegos, since this isn't related to `use-wallet`.
