### ISSUE TITLE
Suppressed stale connector activation

### ISSUE THREAD

**Issue by supermars01** [aragon/use-wallet#72]
When I have connected to any connector, I call connect(id) again and an error will be reported Warning: Suppressed stale connector activation,At this point, I need to call connect(id) again to connect to the wallet normally，Is there any API to disconnect directly?
![image](https://user-images.githubusercontent.com/7869573/101134187-f28dfe00-3644-11eb-901c-974811142fe1.png)

**Comment by sohkai** [comment]
Hi @supermars01, not sure if you saw it, but there's a [`reset()` method](https://github.com/aragon/use-wallet#usewallet) available to reset the connection and disconnect.

**Comment by supermars01** [comment]
> Hi @sohkai ，thank you！I called reset(), but it doesn't seem to work. When I call connect (ID) again, I still report an error of "suppressed stale connector activation". Then I call connect (ID) again to connect normally

**Comment by supermars01** [comment]
Is reset() asynchronous? I tried to call await reset(); and then called connect (ID). No more errors were reported

**Comment by supermars01** [comment]
resolved
