### ISSUE TITLE
useWallet() returns no wallet when metamask is connected to ropsten

### ISSUE THREAD

**Issue by Shirikatsu** [aragon/use-wallet#83]
As title suggests, no account address as the wallet is returned from `useWallet()` when connected to Ropsten using Metamask.

```javascript
const { wallet } = useWallet()

console.log(wallet) // > null
```

**Comment by izayl** [comment]
you can use `chainId` to assign net

```jsx
export default () => (
  <UseWalletProvider
    chainId={1}
    connectors={{
      // This is how connectors get configured
      portis: { dAppId: 'my-dapp-id-123-xyz' },
    }}
  >
    <App />
  </UseWalletProvider>
)
```

`chainId` define you can find in source below:

https://github.com/aragon/use-wallet/blob/f40b18c554d114e5d70de005787826129e5ab557/src/utils.ts#L2-L17

**Comment by supermars01** [comment]
Only one network connection is supported，

**Comment by garythung** [comment]
What's a good strategy for detecting if the user is not on the correct network?

**Comment by WissenIstNacht** [comment]
Hey @garythung

The `useWallet` hook provides an error parameter. You can use that error to detect whether a user is on the wrong network by typechecking the error. Something like this:

```typescript
const { account , error, networkName } = useWallet();

if (error instanceof ChainUnsupportedError) {
  console.log(networkName + " is not enabled");
}
```

**Comment by garythung** [comment]
> Hey @garythung
> 
> The `useWallet` hook provides an error parameter. You can use that error to detect whether a user is on the wrong network by typechecking the error. Something like this:
> 
> ```ts
> const { account , error, networkName } = useWallet();
> 
> if (error instanceof ChainUnsupportedError) {
>   console.log(networkName + " is not enabled");
> }
> ```

I'm using MetaMask connected to mainnet on Desktop and getting

```
chainId: 4,
networkName: "Rinkeby",
```

with `<UseWalletProvider chainID={4}>`.

It's injecting the single allowed network into `useWallet`, not the network the provider is connected to. Is this intended?

**Comment by WissenIstNacht** [comment]
Hey again. The intended behavior is the following:

The `useWallet` hook has to be used in some child of `UseWalletProvider`. That's because `UseWalletProvider` provides a context from which the `useWallet` hook gets information. Thus, you first declare `UseWalletProvider` with the `chainId` on which you want your dApp to run. 

For example, let's say you want to run it on _mainnet_. This would mean you set `chainId=1`. Something like so:

https://github.com/aragon/use-wallet/blob/dffd01ea52f34cbb96b2c2eb707ba69502f00838/examples/simple-connect/index.js#L99-L100

If a user then connect to your application when Metamask is on _rinkeby_, `useWallet` will provide you with a `ChainUnsupportedError`.

**Comment by garythung** [comment]
Gotcha, so in the error catching snippet you shared, using `networkName` is actually wrong because that's the name that the config is set to, not the user's provider's current connection.

**Comment by WissenIstNacht** [comment]
Oh, I think I see the problem now. We may have misunderstood each other. 😅

> that's the name that the config is set to, not the user's provider's current connection.

Exactly. 

> using networkName is actually wrong

Hmm. Sorry, maybe I just expressed myself poorly. How about if I rephrase the error message to:

`console.log("This application runs on " + networkName + ", which is currently not enabled in your Metamask");`

**Comment by garythung** [comment]
Haha, yeah that's right. Thanks for troubleshooting with me
